spring:
   application:
      name: medireco
   profiles:
      active: development
   mvc:
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true
   web:
      resources:
         static-locations: classpath:/assets/
   thymeleaf:
      prefix: classpath:templates/
      check-template-location: true
      mode: HTML
      suffix: .html
      cache: false

mybatis:
   config-location: classpath:mybatis/configuration.xml

         
---
#
# development configuration
#
spring:
   config:
      activate:
         on-profile: development
   devtools:
      livereload:
         enabled: true
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://112.162.205.179:3306/medireco?characterEncoding=utf8
      username: root
      password: webdb
      hikari:
        minimum-idle: 10
        maximum-pool-size: 20
server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true         
logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: INFO

      
---
#
# production configuration
#
spring:
   config:
      activate:
         on-profile: production
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.10.52:3306/medireco?characterEncoding=utf8
      username: medireco
      password: medireco
      hikari:
        minimum-idle: 10
        maximum-pool-size: 20    
server:
   port: 8880
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      me:
         kickscar:
            mysite:
               exception: ERROR